### ISSUE TITLE
more chanels to mirror

### ISSUE THREAD

**Issue by Jokyy** [Mssjim/discord-server-mirror#10]
Hi, Its possible to mirror more than one chanel?  Thank you

**Comment by Mssjim** [comment]
Not for now, but I can implement xD
Would you like to choose more than one channel as "read channel" and send all messages to the "write channel", right?

**Comment by Jokyy** [comment]
> 

Hi, I would like to choose more than  one channel as "read channel"  and more than  one channel as  "write channel".
For example:
I would like to asign 
for "read channel1" "write channel1", 
for "read channel2" "write channel2",
for "read channel3" "write channel3",
for "read channel4" "write channel4",
....
I need 16 channels. If this possible? 
Thank you :)

**Comment by Mssjim** [comment]
Oh, I see. A really server clone xD
Now u can do that 🙏 

Your `settings.json` will look like:

```js
    "readChannel": ["read channel1", "read channel2", "read channel3"],
    "writeChannel": ["write channel1", "write channel2", "write channel3"],
```

You can also use a single read or write channel to mirror multiples channels to only one...

This hasn't been tested many times yet, so any bugs, or suggestions, feel free to ask xD

**Comment by Jokyy** [comment]
Thank you :) I will test it...

**Comment by Jokyy** [comment]
Hi I am tried it and it seems its works, but from some servers and channels it write me  instead the message only this: 
NEW: @deleted-role . Please can you help...thank you.

**Comment by Mssjim** [comment]
Can you check the original message when this occurs? Maybe someone is mentioning a role, and because it doesn't exist on the "write server", it appears as `@deleted-role`.

![image](https://user-images.githubusercontent.com/43995964/205689484-3f75cf4f-fd72-467d-95db-d2b001c3e59e.png)
![image](https://user-images.githubusercontent.com/43995964/205689499-79aebd49-1a2d-4dc9-89c4-a7b3d601ab3a.png)

Something similar happened with user mentions, but as a temporary fix, set `"ignoreMentions": true` to ignore these mentions, I will soon release a better option to be able to just ignore them or show the member/role in question.

![image](https://user-images.githubusercontent.com/43995964/205690545-b072e8af-06ca-4937-b477-75cbe5cb6820.png)
![image](https://user-images.githubusercontent.com/43995964/205690552-26f4f288-2aea-4114-aae6-ee9a78ebbfce.png)
