### ISSUE TITLE
not works for me

### ISSUE THREAD

**Issue by hosseinthd** [Mssjim/discord-server-mirror#14]
hey . whats the problem ? also i use channels id not server
![1](https://user-images.githubusercontent.com/74374853/215551061-1218fc08-469e-420c-ab2b-980f76a45bd2.PNG)
![2](https://user-images.githubusercontent.com/74374853/215551090-24ba545e-142a-4ae7-ab8d-9722363200b5.jpg)

**Comment by Mssjim** [comment]
Hi, sorry for the delay xD
Is your read channel from some big server?
Try testing on a private server, create two channels and use one as a read and the other as a write channel.

It's also important to note that since you're only using one account, messages from that account are ignored. Mirroring test must be done using another account.

![image](https://user-images.githubusercontent.com/43995964/216592307-bec1ccc9-7376-4537-b657-2741f35eff54.png)
![Sem título](https://user-images.githubusercontent.com/43995964/216592323-4e4556f4-64a8-41cd-b4cc-b3b61e4c5b61.png)
