### ISSUE TITLE
Automated restart/reconnect

### ISSUE THREAD

**Issue by Shmalle** [Mssjim/discord-server-mirror#2]
Hey! I have been trying out various mirrors such as yours but all of them have one _error_ in common:
**Stopping to mirror after _some_ time**.

Restarting the script fixes this issue. Hence I like yours the most, I beg you to implement an automated restart to it.
The problem is rather fixable with a reconnect, but a fresh restart of the whole code instead of just a reconnect to websocket is preferred.
Thanks in advance!

**Comment by Mssjim** [comment]
This happens because this use outdated websockets versions as a base, the self accounts core needs updating xD
But as a temporary solution, you can run the "start.bat" or "start.sh" script, which will make all the code to be restarted restart whenever an error occurs, either from websocket, connection or request failed 🙏

**Comment by Shmalle** [comment]
Been running the script since yesterday evening, workign as expected. Big thanks ❤️
