### ISSUE TITLE
Delay leading to wrong order

### ISSUE THREAD

**Issue by Shmalle** [Mssjim/discord-server-mirror#4]
I noticed that the bot takes around 5-10 seconds to copy and redirect a message which absolutely isn't a problem, _if it wouldn't mess up the order within._ I noticed that, when sending messages, it sometimes changes the order in which they were originally sent.

**Comment by Mssjim** [comment]
This happened because before sending, it is shown that the self is typing for a few moments (~200ms/char), but as each person has a different typing time, the origin order is lost. I added a kind of queue so that the original order of messages is always kept :pray: and if you don't need that "typing information", now you can disable it in the `settings.json` file, setting `typing` to `false`, so the copies will be in real time.

**Comment by Shmalle** [comment]
Awesome, thanks!
